package com.dtmining.latte.mk.ui.recycler;
/**
 * author:songwenming
 * Date:2018/9/29
 * Description:
 */
public enum MultipleFields {
    TITLE,
    ITEM_TYPE,
    TEXT,
    //用药历史中的药品名，或者是“开箱操作”？？
    MEDICINE_NAME,
    ATIME,
    IMAGE_URL,
    //resId
    BUTTON_IMAGE,
    BUTTON_NAME,
    BANNERS,
    BANNERS_INTEGER,
    SPAN_SIZE,
    ID,
    NAME,
    TAG,

    TEL,
    MEDICINECODE,
    MEDICINEID,
    MEDICINECOUNT,
    MEDICINENAME,
    MEDICINEIMGURL,
    MEDICINEVALIDITY,
    BOXID,
    MEDICINEPAUSE,
    MEDICINEUSERTIME,
    OVERDUE,
    ONUSE,
    PAUSE,
    MEDICINE_USERCOUNT,//统计总数
    MEDICINE_USERTIME,//统计时长
    REACTION,
    MEDICINE_USETIME,
    MEDICINE_USE_MESSAGE_TITLE,
    MEDICINE_USE_MESSAGE_TIME,
    MEDICINE_USE_MESSAGE_CONTENT,

    MEDICINE_SUPPLY_MESSAGE_TITLE,
    MEDICINE_SUPPLY_MESSAGE_TIME,
    MEDICINE_SUPPLY_MESSAGE_CONTENT,

    MEDICINE_OVERDUE_MESSAGE_TITLE,
    MEDICINE_OVERDUE_MESSAGE_TIME,
    MEDICINE_OVERDUE_MESSAGE_CONTENT




}
