package com.dtmining.latte.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "user_profile".
*/
public class UserProfileDao extends AbstractDao<UserProfile, Long> {

    public static final String TABLENAME = "user_profile";

    /**
     * Properties of entity UserProfile.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Tel = new Property(0, long.class, "tel", true, "_id");
        public final static Property Username = new Property(1, String.class, "username", false, "USERNAME");
        public final static Property Pwd = new Property(2, String.class, "pwd", false, "PWD");
        public final static Property Role = new Property(3, String.class, "role", false, "ROLE");
        public final static Property Entry_way = new Property(4, String.class, "entry_way", false, "ENTRY_WAY");
    }


    public UserProfileDao(DaoConfig config) {
        super(config);
    }
    
    public UserProfileDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"user_profile\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: tel
                "\"USERNAME\" TEXT," + // 1: username
                "\"PWD\" TEXT," + // 2: pwd
                "\"ROLE\" TEXT," + // 3: role
                "\"ENTRY_WAY\" TEXT);"); // 4: entry_way
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"user_profile\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserProfile entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTel());
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
 
        String pwd = entity.getPwd();
        if (pwd != null) {
            stmt.bindString(3, pwd);
        }
 
        String role = entity.getRole();
        if (role != null) {
            stmt.bindString(4, role);
        }
 
        String entry_way = entity.getEntry_way();
        if (entry_way != null) {
            stmt.bindString(5, entry_way);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserProfile entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTel());
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
 
        String pwd = entity.getPwd();
        if (pwd != null) {
            stmt.bindString(3, pwd);
        }
 
        String role = entity.getRole();
        if (role != null) {
            stmt.bindString(4, role);
        }
 
        String entry_way = entity.getEntry_way();
        if (entry_way != null) {
            stmt.bindString(5, entry_way);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public UserProfile readEntity(Cursor cursor, int offset) {
        UserProfile entity = new UserProfile( //
            cursor.getLong(offset + 0), // tel
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // username
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pwd
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // role
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // entry_way
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserProfile entity, int offset) {
        entity.setTel(cursor.getLong(offset + 0));
        entity.setUsername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPwd(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRole(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEntry_way(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserProfile entity, long rowId) {
        entity.setTel(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserProfile entity) {
        if(entity != null) {
            return entity.getTel();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserProfile entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
